/**
 * Fulham Player Statistics Data
 * Source: Football API - Match ID: 2023473988977823744 (Fulham vs Southampton)
 */

const fulhamPlayers = [
    {
        id: "1897728044861489153",
        name: "Lecomte B.",
        fullName: "Lecomte Benjamin",
        position: "Goalkeeper",
        team: "Fulham",
        teamLogo: "../Assets/TeamLogos/Premier league/Fulham.png",
        playerPhoto: "../Assets/PlayerPhotos/Football/Fulham/Lecomte Benjamin.jpg",
        stats: {
            rating: 7.5,
            saves: 5,
            shotsOnTargetAgainst: 7,
            goalsAgainst: 2,
            shotsTotal: null,
            expectedGoals: null,
            passesAccurate: 22,
            passesTotal: 27,
            passesAccuracy: "81%",
            touchesTotal: 35,
            touchesBoxOpposite: null,
            dribblesWon: null,
            dribblesTotal: null,
            dribblesSuccess: null,
            duelsTotal: 1,
            goals: null,
            xGOT: null,
            shotsOnTarget: null,
            shotsOffTarget: null,
            shotsBlocked: null,
            shotsBoxIn: null,
            shotsBoxOut: null,
            shotsHead: null
        }
    },
    {
        id: "1897743760918577152",
        name: "Muniz R.",
        fullName: "Rodrigo Muniz",
        position: "Forward",
        team: "Fulham",
        teamLogo: "../Assets/TeamLogos/Premier league/Fulham.png",
        playerPhoto: "../Assets/PlayerPhotos/Football/Fulham/Rodrigo Muniz.jpg",
        stats: {
            rating: 7.6,
            shotsTotal: 6,
            expectedGoals: 0.52,
            passesAccurate: 6,
            passesTotal: 9,
            passesAccuracy: "67%",
            touchesTotal: 29,
            touchesBoxOpposite: 10,
            dribblesWon: 0,
            dribblesTotal: 2,
            dribblesSuccess: "0%",
            duelsTotal: 18,
            goals: 0,
            xGOT: 0.45,
            shotsOnTarget: 3,
            shotsOffTarget: 2,
            shotsBlocked: 1,
            shotsBoxIn: 5,
            shotsBoxOut: 1,
            shotsHead: 1
        }
    },
    {
        id: "1897734875788869633",
        name: "Reed H.",
        fullName: "Reed Harrison",
        position: "Midfielder",
        team: "Fulham",
        teamLogo: "../Assets/TeamLogos/Premier league/Fulham.png",
        playerPhoto: "../Assets/PlayerPhotos/Football/Fulham/Reed Harrison.jpg",
        stats: {
            rating: 7.6,
            shotsTotal: 2,
            expectedGoals: 0.09,
            passesAccurate: 76,
            passesTotal: 80,
            passesAccuracy: "95%",
            touchesTotal: 110,
            touchesBoxOpposite: 2,
            dribblesWon: 1,
            dribblesTotal: 2,
            dribblesSuccess: "50%",
            duelsTotal: 7,
            goals: 0,
            xGOT: 0.07,
            shotsOnTarget: 1,
            shotsOffTarget: 1,
            shotsBlocked: 0,
            shotsBoxIn: 1,
            shotsBoxOut: 1,
            shotsHead: 0
        }
    },
    {
        id: "1897728044861489153",
        name: "Lecomte B.",
        fullName: "Lecomte Benjamin",
        position: "Goalkeeper",
        team: "Fulham",
        teamLogo: "../Assets/TeamLogos/Premier league/Fulham.png",
        playerPhoto: "../Assets/PlayerPhotos/Football/Fulham/Lecomte Benjamin.jpg",
        stats: {
            rating: 7.5,
            shotsTotal: null,
            expectedGoals: null,
            passesAccurate: 25,
            passesTotal: 32,
            passesAccuracy: "78%",
            touchesTotal: 39,
            touchesBoxOpposite: null,
            dribblesWon: null,
            dribblesTotal: null,
            dribblesSuccess: null,
            duelsTotal: 0,
            goals: null,
            xGOT: null,
            shotsOnTarget: null,
            shotsOffTarget: null,
            shotsBlocked: null,
            shotsBoxIn: null,
            shotsBoxOut: null,
            shotsHead: null
        }
    },
    {
        id: "1897731018522361856",
        name: "Andersen J.",
        fullName: "Andersen Joachim",
        position: "Defender",
        team: "Fulham",
        teamLogo: "../Assets/TeamLogos/Premier league/Fulham.png",
        playerPhoto: "../Assets/PlayerPhotos/Football/Fulham/Andersen Joachim.jpg",
        stats: {
            rating: 7.3,
            shotsTotal: 2,
            expectedGoals: 0.12,
            passesAccurate: 87,
            passesTotal: 96,
            passesAccuracy: "91%",
            touchesTotal: 114,
            touchesBoxOpposite: 3,
            dribblesWon: null,
            dribblesTotal: null,
            dribblesSuccess: null,
            duelsTotal: 16,
            goals: 0,
            xGOT: 0.10,
            shotsOnTarget: 1,
            shotsOffTarget: 0,
            shotsBlocked: 1,
            shotsBoxIn: 1,
            shotsBoxOut: 1,
            shotsHead: 1
        }
    },
    {
        id: "1897700077255000064",
        name: "Bobb O.",
        fullName: "Bobb Oscar",
        position: "Midfielder",
        team: "Fulham",
        teamLogo: "../Assets/TeamLogos/Premier league/Fulham.png",
        playerPhoto: "../Assets/PlayerPhotos/Football/Fulham/Bobb Oscar.jpg",
        stats: {
            rating: 7.0,
            shotsTotal: 3,
            expectedGoals: 0.21,
            passesAccurate: 40,
            passesTotal: 48,
            passesAccuracy: "83%",
            touchesTotal: 63,
            touchesBoxOpposite: 13,
            dribblesWon: 2,
            dribblesTotal: 2,
            dribblesSuccess: "100%",
            duelsTotal: 7,
            goals: 0,
            xGOT: 0.18,
            shotsOnTarget: 2,
            shotsOffTarget: 1,
            shotsBlocked: 0,
            shotsBoxIn: 3,
            shotsBoxOut: 0,
            shotsHead: 0
        }
    },
    {
        id: "1897679629330939904",
        name: "Cairney T.",
        fullName: "Cairney Tom",
        position: "Midfielder",
        team: "Fulham",
        teamLogo: "../Assets/TeamLogos/Premier league/Fulham.png",
        playerPhoto: "../Assets/PlayerPhotos/Football/Fulham/Cairney Tom.jpg",
        stats: {
            rating: 6.9,
            shotsTotal: 2,
            expectedGoals: 0.06,
            passesAccurate: 74,
            passesTotal: 79,
            passesAccuracy: "94%",
            touchesTotal: 91,
            touchesBoxOpposite: null,
            dribblesWon: 1,
            dribblesTotal: 1,
            dribblesSuccess: "100%",
            duelsTotal: 5,
            goals: 0,
            xGOT: 0.05,
            shotsOnTarget: 1,
            shotsOffTarget: 1,
            shotsBlocked: 0,
            shotsBoxIn: 1,
            shotsBoxOut: 1,
            shotsHead: 0
        }
    },
    {
        id: "1897733303138779137",
        name: "Castagne T.",
        fullName: "Castagne Timothy",
        position: "Defender",
        team: "Fulham",
        teamLogo: "../Assets/TeamLogos/Premier league/Fulham.png",
        playerPhoto: "../Assets/PlayerPhotos/Football/Fulham/Castagne Timothy.jpg",
        stats: {
            rating: 6.9,
            shotsTotal: 1,
            expectedGoals: 0.05,
            passesAccurate: 42,
            passesTotal: 47,
            passesAccuracy: "89%",
            touchesTotal: 79,
            touchesBoxOpposite: 7,
            dribblesWon: 0,
            dribblesTotal: 1,
            dribblesSuccess: "0%",
            duelsTotal: 8,
            goals: 0,
            xGOT: 0.04,
            shotsOnTarget: 1,
            shotsOffTarget: 0,
            shotsBlocked: 0,
            shotsBoxIn: 1,
            shotsBoxOut: 0,
            shotsHead: 0
        }
    },
    {
        id: "1897692255825952768",
        name: "Smith Rowe E.",
        fullName: "Smith Rowe Emile",
        position: "Midfielder",
        team: "Fulham",
        teamLogo: "../Assets/TeamLogos/Premier league/Fulham.png",
        playerPhoto: "../Assets/PlayerPhotos/Football/Fulham/Smith Rowe Emile.jpg",
        stats: {
            rating: 6.8,
            shotsTotal: null,
            expectedGoals: null,
            passesAccurate: 36,
            passesTotal: 42,
            passesAccuracy: "86%",
            touchesTotal: 46,
            touchesBoxOpposite: 2,
            dribblesWon: 1,
            dribblesTotal: 1,
            dribblesSuccess: "100%",
            duelsTotal: 4,
            goals: null,
            xGOT: null,
            shotsOnTarget: null,
            shotsOffTarget: null,
            shotsBlocked: null,
            shotsBoxIn: null,
            shotsBoxOut: null,
            shotsHead: null
        }
    },
    {
        id: "1897731511424385027",
        name: "Iwobi A.",
        fullName: "Iwobi Alex",
        position: "Midfielder",
        team: "Fulham",
        teamLogo: "../Assets/TeamLogos/Premier league/Fulham.png",
        playerPhoto: "../Assets/PlayerPhotos/Football/Fulham/Iwobi Alex.jpg",
        stats: {
            rating: 6.7,
            shotsTotal: 2,
            expectedGoals: 0.11,
            passesAccurate: 24,
            passesTotal: 27,
            passesAccuracy: "89%",
            touchesTotal: 38,
            touchesBoxOpposite: 3,
            dribblesWon: 0,
            dribblesTotal: 2,
            dribblesSuccess: "0%",
            duelsTotal: 4,
            goals: 0,
            xGOT: 0.09,
            shotsOnTarget: 1,
            shotsOffTarget: 1,
            shotsBlocked: 0,
            shotsBoxIn: 2,
            shotsBoxOut: 0,
            shotsHead: 0
        }
    },
    {
        id: "1897691124680884225",
        name: "Sessegnon R.",
        fullName: "Sessegnon Ryan",
        position: "Defender",
        team: "Fulham",
        teamLogo: "../Assets/TeamLogos/Premier league/Fulham.png",
        playerPhoto: "../Assets/PlayerPhotos/Football/Fulham/Sessegnon Ryan.jpg",
        stats: {
            rating: 6.7,
            shotsTotal: 4,
            expectedGoals: 0.42,
            passesAccurate: 40,
            passesTotal: 45,
            passesAccuracy: "89%",
            touchesTotal: 74,
            touchesBoxOpposite: 6,
            dribblesWon: null,
            dribblesTotal: null,
            dribblesSuccess: null,
            duelsTotal: 6,
            goals: 0,
            xGOT: 0.35,
            shotsOnTarget: 2,
            shotsOffTarget: 1,
            shotsBlocked: 1,
            shotsBoxIn: 3,
            shotsBoxOut: 1,
            shotsHead: 0
        }
    },
    {
        id: "1897681526716628992",
        name: "Jimenez R.",
        fullName: "Jimenez Raul",
        position: "Forward",
        team: "Fulham",
        teamLogo: "../Assets/TeamLogos/Premier league/Fulham.png",
        playerPhoto: "../Assets/PlayerPhotos/Football/Fulham/Jimenez Raul.jpg",
        stats: {
            rating: 6.5,
            shotsTotal: null,
            expectedGoals: null,
            passesAccurate: 0,
            passesTotal: 1,
            passesAccuracy: "0%",
            touchesTotal: 3,
            touchesBoxOpposite: 1,
            dribblesWon: null,
            dribblesTotal: null,
            dribblesSuccess: null,
            duelsTotal: 2,
            goals: null,
            xGOT: null,
            shotsOnTarget: null,
            shotsOffTarget: null,
            shotsBlocked: null,
            shotsBoxIn: null,
            shotsBoxOut: null,
            shotsHead: null
        }
    },
    {
        id: "1897695203754770432",
        name: "Cuenca J.",
        fullName: "Cuenca Jorge",
        position: "Defender",
        team: "Fulham",
        teamLogo: "../Assets/TeamLogos/Premier league/Fulham.png",
        playerPhoto: "../Assets/PlayerPhotos/Football/Fulham/Cuenca Jorge.jpg",
        stats: {
            rating: 6.5,
            shotsTotal: 1,
            expectedGoals: 0.03,
            passesAccurate: 60,
            passesTotal: 65,
            passesAccuracy: "92%",
            touchesTotal: 79,
            touchesBoxOpposite: 1,
            dribblesWon: null,
            dribblesTotal: null,
            dribblesSuccess: null,
            duelsTotal: 5,
            goals: 0,
            xGOT: 0.02,
            shotsOnTarget: 0,
            shotsOffTarget: 1,
            shotsBlocked: 0,
            shotsBoxIn: 0,
            shotsBoxOut: 1,
            shotsHead: 1
        }
    }
];

// Export for use in other modules
if (typeof module !== 'undefined' && module.exports) {
    module.exports = fulhamPlayers;
}
