/**
 * Manchester City Player Statistics Data
 * Source: Football API - Match ID: 1935259476760469504 (Man City vs Nottingham)
 */

const manchesterCityPlayers = [
    {
        id: "home-31",
        name: "Trafford J.",
        fullName: "Trafford James",
        position: "Goalkeeper",
        team: "Manchester City",
        teamLogo: "../Assets/TeamLogos/Premier league/Man city.png",
        playerPhoto: "../Assets/PlayerPhotos/Football/ManchesterCity2/Trafford James.jpg",
        stats: {
            rating: 7.4,
            saves: 3,
            shotsOnTargetAgainst: 3,
            goalsAgainst: 0,
            shotsTotal: null,
            expectedGoals: null,
            passesAccurate: 28,
            passesTotal: 34,
            passesAccuracy: "82%",
            touchesTotal: 38,
            touchesBoxOpposite: null,
            dribblesWon: null,
            dribblesTotal: null,
            dribblesSuccess: null,
            duelsTotal: 2,
            goals: null,
            xGOT: null,
            shotsOnTarget: null,
            shotsOffTarget: null,
            shotsBlocked: null,
            shotsBoxIn: null,
            shotsBoxOut: null,
            shotsHead: null
        }
    },
    {
        id: "1897739615272697856",
        name: "Foden P.",
        fullName: "Foden Phil",
        position: "Midfielder",
        team: "Manchester City",
        teamLogo: "../Assets/TeamLogos/Premier league/Man city.png",
        playerPhoto: "../Assets/PlayerPhotos/Football/ManchesterCity2/Foden Phil.jpg",
        stats: {
            rating: 7.2,
            shotsTotal: 2,
            expectedGoals: 0.05,
            passesAccurate: 55,
            passesTotal: 63,
            passesAccuracy: "87%",
            touchesTotal: 76,
            touchesBoxOpposite: 4,
            dribblesWon: 1,
            dribblesTotal: 1,
            dribblesSuccess: "100%",
            duelsTotal: 4,
            goals: 2,
            penaltyGoals: 1, // 1 z toho je penalta
            xGOT: 0.04,
            shotsOnTarget: 1,
            shotsOffTarget: 1,
            shotsBlocked: 0,
            shotsBoxIn: 1,
            shotsBoxOut: 1,
            shotsHead: 0
        }
    },
    {
        id: "1897684426570334208",
        name: "Dias R.",
        fullName: "Dias Ruben",
        position: "Defender",
        team: "Manchester City",
        teamLogo: "../Assets/TeamLogos/Premier league/Man city.png",
        playerPhoto: "../Assets/PlayerPhotos/Football/ManchesterCity2/Dias Ruben.jpg",
        stats: {
            rating: 7.4,
            shotsTotal: null,
            expectedGoals: null,
            passesAccurate: 81,
            passesTotal: 88,
            passesAccuracy: "92%",
            touchesTotal: 99,
            touchesBoxOpposite: null,
            dribblesWon: 0,
            dribblesTotal: 1,
            dribblesSuccess: "0%",
            duelsTotal: 5,
            goals: null,
            xGOT: null,
            shotsOnTarget: null,
            shotsOffTarget: null,
            shotsBlocked: null,
            shotsBoxIn: null,
            shotsBoxOut: null,
            shotsHead: null
        }
    },
    {
        id: "1897739566216118272",
        name: "Haaland E.",
        fullName: "Haaland Erling Braut",
        position: "Forward",
        team: "Manchester City",
        teamLogo: "Assets/TeamLogos/Premier league/Man city.png",
        playerPhoto: "Assets/PlayerPhotos/Football/ManchesterCity2/Haaland Erling Braut.jpg",
        stats: {
            rating: 5.9,
            shotsTotal: 2,
            expectedGoals: 0.10,
            passesAccurate: 5,
            passesTotal: 7,
            passesAccuracy: "71%",
            touchesTotal: 14,
            touchesBoxOpposite: 7,
            dribblesWon: null,
            dribblesTotal: null,
            dribblesSuccess: null,
            duelsTotal: 5,
            goals: 0,
            xGOT: 0.08,
            shotsOnTarget: 1,
            shotsOffTarget: 1,
            shotsBlocked: 0,
            shotsBoxIn: 2,
            shotsBoxOut: 0,
            shotsHead: 1
        }
    },
    {
        id: "1897732563787841539",
        name: "Silva B.",
        fullName: "Silva Bernardo",
        position: "Midfielder",
        team: "Manchester City",
        teamLogo: "../Assets/TeamLogos/Premier league/Man city.png",
        playerPhoto: "../Assets/PlayerPhotos/Football/ManchesterCity2/Silva Bernardo.jpg",
        stats: {
            rating: 8.0,
            shotsTotal: 5,
            expectedGoals: 0.28,
            passesAccurate: 107,
            passesTotal: 112,
            passesAccuracy: "96%",
            touchesTotal: 130,
            touchesBoxOpposite: 11,
            dribblesWon: 2,
            dribblesTotal: 3,
            dribblesSuccess: "67%",
            duelsTotal: 8,
            goals: 1,
            xGOT: 0.32,
            shotsOnTarget: 3,
            shotsOffTarget: 1,
            shotsBlocked: 1,
            shotsBoxIn: 4,
            shotsBoxOut: 1,
            shotsHead: 0
        }
    },
    {
        id: "1897689487811805184",
        name: "Rodri",
        fullName: "Rodri",
        position: "Midfielder",
        team: "Manchester City",
        teamLogo: "../Assets/TeamLogos/Premier league/Man city.png",
        playerPhoto: "../Assets/PlayerPhotos/Football/ManchesterCity2/Rodri.jpg",
        stats: {
            rating: 8.2,
            shotsTotal: 3,
            expectedGoals: 0.37,
            passesAccurate: 100,
            passesTotal: 106,
            passesAccuracy: "94%",
            touchesTotal: 116,
            touchesBoxOpposite: 3,
            dribblesWon: null,
            dribblesTotal: null,
            dribblesSuccess: null,
            duelsTotal: 9,
            goals: 0,
            xGOT: 0.29,
            shotsOnTarget: 2,
            shotsOffTarget: 1,
            shotsBlocked: 0,
            shotsBoxIn: 2,
            shotsBoxOut: 1,
            shotsHead: 0
        }
    },
    {
        id: "1897700133601280000",
        name: "Nunes M.",
        fullName: "Nunes Matheus Luiz",
        position: "Midfielder",
        team: "Manchester City",
        teamLogo: "../Assets/TeamLogos/Premier league/Man city.png",
        playerPhoto: "../Assets/PlayerPhotos/Football/ManchesterCity2/Nunes Matheus Luiz.jpg",
        stats: {
            rating: 7.0,
            shotsTotal: null,
            expectedGoals: null,
            passesAccurate: 70,
            passesTotal: 79,
            passesAccuracy: "89%",
            touchesTotal: 107,
            touchesBoxOpposite: 7,
            dribblesWon: 3,
            dribblesTotal: 6,
            dribblesSuccess: "50%",
            duelsTotal: 12,
            goals: null,
            xGOT: null,
            shotsOnTarget: null,
            shotsOffTarget: null,
            shotsBlocked: null,
            shotsBoxIn: null,
            shotsBoxOut: null,
            shotsHead: null
        }
    },
    {
        id: "1897695264471515136",
        name: "Doku J.",
        fullName: "Doku Jeremy",
        position: "Forward",
        team: "Manchester City",
        teamLogo: "../Assets/TeamLogos/Premier league/Man city.png",
        playerPhoto: "../Assets/PlayerPhotos/Football/ManchesterCity2/Doku Jeremy.jpg",
        stats: {
            rating: 6.7,
            shotsTotal: 1,
            expectedGoals: 0.04,
            passesAccurate: 6,
            passesTotal: 7,
            passesAccuracy: "86%",
            touchesTotal: 13,
            touchesBoxOpposite: null,
            dribblesWon: 0,
            dribblesTotal: 1,
            dribblesSuccess: "0%",
            duelsTotal: 4,
            goals: 0,
            xGOT: 0.03,
            shotsOnTarget: 0,
            shotsOffTarget: 1,
            shotsBlocked: 0,
            shotsBoxIn: 1,
            shotsBoxOut: 0,
            shotsHead: 0
        }
    },
    {
        id: "1897750543393357824",
        name: "Savinho",
        fullName: "Savinho",
        position: "Forward",
        team: "Manchester City",
        teamLogo: "Assets/TeamLogos/Premier league/Man city.png",
        playerPhoto: "Assets/PlayerPhotos/Football/ManchesterCity2/Savinho.jpg",
        stats: {
            rating: 6.3,
            shotsTotal: 2,
            expectedGoals: 0.49,
            passesAccurate: 3,
            passesTotal: 4,
            passesAccuracy: "75%",
            touchesTotal: 14,
            touchesBoxOpposite: 5,
            dribblesWon: 0,
            dribblesTotal: 2,
            dribblesSuccess: "0%",
            duelsTotal: 2,
            goals: 0,
            xGOT: 0.38,
            shotsOnTarget: 1,
            shotsOffTarget: 0,
            shotsBlocked: 1,
            shotsBoxIn: 2,
            shotsBoxOut: 0,
            shotsHead: 0
        }
    },
    {
        id: "1897756675314810883",
        name: "Khusanov A.",
        fullName: "Khusanov Abdukodir",
        position: "Defender",
        team: "Manchester City",
        teamLogo: "../Assets/TeamLogos/Premier league/Man city.png",
        playerPhoto: "../Assets/PlayerPhotos/Football/ManchesterCity2/Khusanov Abdukodir.jpg",
        stats: {
            rating: 6.4,
            shotsTotal: null,
            expectedGoals: null,
            passesAccurate: 8,
            passesTotal: 9,
            passesAccuracy: "89%",
            touchesTotal: 12,
            touchesBoxOpposite: null,
            dribblesWon: 0,
            dribblesTotal: 1,
            dribblesSuccess: "0%",
            duelsTotal: 1,
            goals: null,
            xGOT: null,
            shotsOnTarget: null,
            shotsOffTarget: null,
            shotsBlocked: null,
            shotsBoxIn: null,
            shotsBoxOut: null,
            shotsHead: null
        }
    }
];

// Export for use in other modules
if (typeof module !== 'undefined' && module.exports) {
    module.exports = manchesterCityPlayers;
}
